### PR TITLE
Add config to disable custom handling

### PR DESCRIPTION
**Pull request by alistair3149**
- Add config to disable custom handling to default details and summary behavior
- Add MW 1.39+ support

### CODE REVIEW

**Comment by kirb** [comment]
Thanks heaps for the PR! Presumably the CSS won't work at all prior to 1.41 since it makes use of Codex tokens. Does the CSS compile and look correct enough in your testing? If not, should it either have fallback values, or should we treat compatibility mode as being `false` if < 1.41?

**Comment by alistair3149** [comment]
Yeah most of those tokens are not available prior to 1.41. So the whole `ext.details.styles` stylesheet won't work.
Hmm there are two ways to handle it:
- Ignore the config and keep compatibility mode off < 1.41
- Use the `default(@my-variable, #000)` syntax to handle Codex tokens for now. You can find the [values here](https://github.com/wikimedia/mediawiki/blob/master/resources/lib/codex-design-tokens/theme-wikimedia-ui.less).

**Comment by kirb** [comment]
I gave it an extremely quick test on SCW (which looks awesome with the use of `<details>`, by the way :wink:) and indeed, the less compiler is unhappy about it. 

```css
/*
[a68313bb04aeeb4484651183] 2024-10-31 07:00:57: Fatal exception of type "Less_Exception_Compiler"

Problematic modules: {"ext.details.styles":"error"}
*/
```

I'll have to see if I can come up with something without needing to do a full MW 1.39 test install since I'm pretty busy currently, unless you're ok with giving it a go? I figure the `default()` approach is simple enough, if less is ok with undefined variables there (I'm not the most familiar with less).

**Comment by alistair3149** [comment]
I added the `default()` handling to the PR, but I don't have access to my 1.39 dev environment for the week so I am unable to test it sadly.

**Comment by kirb** [comment]
That was quick, thanks! I'll give it my approval but I'll wait till one of us has a chance to test before merging/releasing. I might get a moment to this weekend.

**Review by kirb — APPROVED** [review]

**Comment by alistair3149** [comment]
Okay I tested it on 1.39 and it seems the `default()` method did not work.
Instead, I defined the LESS variables before the `import` so that they can be overridden with the imported variables.
Also fix the issue where `.mw-collapsible-text` is not styled as a link.

**Review by kirb — APPROVED** [review]

**Comment by kirb** [comment]
Merged, thanks! 🚀

**Pull request merged**
